---
Exception (message='test_exception'):
  message: Boo!
  cause: 
